server:
  port: 8080


spring:
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      strict: false
      druid:
        # 连接池的配置信息
        type: com.alibaba.druid.pool.DruidDataSource
        # 初始化大小，最小等待连接数量，最大等待连接数量，最大连接数
        min-idle: 1
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        initial-size: 1
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        pool-prepared-statements: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        max-pool-prepared-statement-per-connection-size: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        # use-global-data-source-stat: true
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:13306/spring_study?characterEncoding=utf8
            username: root
            password: walp1314
        slave_1:
          driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:13307/spring_study1?characterEncoding=utf8
            username: root
            password: walp1314


druid:
  allow: #允许登陆的IP地址
    ip: 127.0.0.1
  login: #登陆的账户密码
    user_name: root
    password: root

logging:
  file: ./logs/spring-study-test-prod.log
  level:
    root: info
    org.springframework.web: info
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
    rolling-file-name: "spring-study-dev.%d{dd-MM-yyyy}.log"